version: '3.1'
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=pass
  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/news
      - SPRING_DATASOURCE_USERNAME=news
      - SPRING_DATASOURCE_PASSWORD=pass