spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  request:
    timeout: 200
    period: 300000
    delay: 200
  jwt:
    secret: 92a2a6768af24ba552e6f5550226252f
    tokenTTL: 100
    refreshTTL: 1000000
    header: Authorization