spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/default
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  request:
    timeout: 200
    period: 300000
